export interface CountryMeta {
  name: string;
  code: string; // ISO 3166-1 alpha-2
  code3: string; // ISO 3166-1 alpha-3
  region: string;
  subregion: string;
  passportColor: string;
  flagEmoji: string;
  population?: number;
  gdpPerCapita?: number;
  hdi?: number;
}

// Map from full country name (as in CSV) to metadata
export const COUNTRIES: Record<string, CountryMeta> = {
  "Afghanistan": { name: "Afghanistan", code: "AF", code3: "AFG", region: "Asia", subregion: "Southern Asia", passportColor: "green", flagEmoji: "🇦🇫" },
  "Albania": { name: "Albania", code: "AL", code3: "ALB", region: "Europe", subregion: "Southern Europe", passportColor: "red", flagEmoji: "🇦🇱" },
  "Algeria": { name: "Algeria", code: "DZ", code3: "DZA", region: "Africa", subregion: "Northern Africa", passportColor: "green", flagEmoji: "🇩🇿" },
  "Andorra": { name: "Andorra", code: "AD", code3: "AND", region: "Europe", subregion: "Southern Europe", passportColor: "blue", flagEmoji: "🇦🇩" },
  "Angola": { name: "Angola", code: "AO", code3: "AGO", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇦🇴" },
  "Antigua and Barbuda": { name: "Antigua and Barbuda", code: "AG", code3: "ATG", region: "Americas", subregion: "Caribbean", passportColor: "blue", flagEmoji: "🇦🇬" },
  "Argentina": { name: "Argentina", code: "AR", code3: "ARG", region: "Americas", subregion: "South America", passportColor: "blue", flagEmoji: "🇦🇷" },
  "Armenia": { name: "Armenia", code: "AM", code3: "ARM", region: "Asia", subregion: "Western Asia", passportColor: "blue", flagEmoji: "🇦🇲" },
  "Australia": { name: "Australia", code: "AU", code3: "AUS", region: "Oceania", subregion: "Australia and New Zealand", passportColor: "blue", flagEmoji: "🇦🇺" },
  "Austria": { name: "Austria", code: "AT", code3: "AUT", region: "Europe", subregion: "Western Europe", passportColor: "red", flagEmoji: "🇦🇹" },
  "Azerbaijan": { name: "Azerbaijan", code: "AZ", code3: "AZE", region: "Asia", subregion: "Western Asia", passportColor: "green", flagEmoji: "🇦🇿" },
  "Bahamas": { name: "Bahamas", code: "BS", code3: "BHS", region: "Americas", subregion: "Caribbean", passportColor: "blue", flagEmoji: "🇧🇸" },
  "Bahrain": { name: "Bahrain", code: "BH", code3: "BHR", region: "Asia", subregion: "Western Asia", passportColor: "red", flagEmoji: "🇧🇭" },
  "Bangladesh": { name: "Bangladesh", code: "BD", code3: "BGD", region: "Asia", subregion: "Southern Asia", passportColor: "green", flagEmoji: "🇧🇩" },
  "Barbados": { name: "Barbados", code: "BB", code3: "BRB", region: "Americas", subregion: "Caribbean", passportColor: "blue", flagEmoji: "🇧🇧" },
  "Belarus": { name: "Belarus", code: "BY", code3: "BLR", region: "Europe", subregion: "Eastern Europe", passportColor: "blue", flagEmoji: "🇧🇾" },
  "Belgium": { name: "Belgium", code: "BE", code3: "BEL", region: "Europe", subregion: "Western Europe", passportColor: "red", flagEmoji: "🇧🇪" },
  "Belize": { name: "Belize", code: "BZ", code3: "BLZ", region: "Americas", subregion: "Central America", passportColor: "blue", flagEmoji: "🇧🇿" },
  "Benin": { name: "Benin", code: "BJ", code3: "BEN", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇧🇯" },
  "Bhutan": { name: "Bhutan", code: "BT", code3: "BTN", region: "Asia", subregion: "Southern Asia", passportColor: "green", flagEmoji: "🇧🇹" },
  "Bolivia": { name: "Bolivia", code: "BO", code3: "BOL", region: "Americas", subregion: "South America", passportColor: "blue", flagEmoji: "🇧🇴" },
  "Bosnia and Herzegovina": { name: "Bosnia and Herzegovina", code: "BA", code3: "BIH", region: "Europe", subregion: "Southern Europe", passportColor: "blue", flagEmoji: "🇧🇦" },
  "Botswana": { name: "Botswana", code: "BW", code3: "BWA", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇧🇼" },
  "Brazil": { name: "Brazil", code: "BR", code3: "BRA", region: "Americas", subregion: "South America", passportColor: "blue", flagEmoji: "🇧🇷" },
  "Brunei": { name: "Brunei", code: "BN", code3: "BRN", region: "Asia", subregion: "South-Eastern Asia", passportColor: "green", flagEmoji: "🇧🇳" },
  "Bulgaria": { name: "Bulgaria", code: "BG", code3: "BGR", region: "Europe", subregion: "Eastern Europe", passportColor: "red", flagEmoji: "🇧🇬" },
  "Burkina Faso": { name: "Burkina Faso", code: "BF", code3: "BFA", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇧🇫" },
  "Burundi": { name: "Burundi", code: "BI", code3: "BDI", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇧🇮" },
  "Cambodia": { name: "Cambodia", code: "KH", code3: "KHM", region: "Asia", subregion: "South-Eastern Asia", passportColor: "blue", flagEmoji: "🇰🇭" },
  "Cameroon": { name: "Cameroon", code: "CM", code3: "CMR", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇨🇲" },
  "Canada": { name: "Canada", code: "CA", code3: "CAN", region: "Americas", subregion: "Northern America", passportColor: "blue", flagEmoji: "🇨🇦" },
  "Cape Verde": { name: "Cape Verde", code: "CV", code3: "CPV", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇨🇻" },
  "Central African Republic": { name: "Central African Republic", code: "CF", code3: "CAF", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇨🇫" },
  "Chad": { name: "Chad", code: "TD", code3: "TCD", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇹🇩" },
  "Chile": { name: "Chile", code: "CL", code3: "CHL", region: "Americas", subregion: "South America", passportColor: "red", flagEmoji: "🇨🇱" },
  "China": { name: "China", code: "CN", code3: "CHN", region: "Asia", subregion: "Eastern Asia", passportColor: "red", flagEmoji: "🇨🇳" },
  "Colombia": { name: "Colombia", code: "CO", code3: "COL", region: "Americas", subregion: "South America", passportColor: "blue", flagEmoji: "🇨🇴" },
  "Comoros": { name: "Comoros", code: "KM", code3: "COM", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇰🇲" },
  "Congo": { name: "Congo", code: "CG", code3: "COG", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇨🇬" },
  "Congo (Dem. Rep.)": { name: "Congo (Dem. Rep.)", code: "CD", code3: "COD", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇨🇩" },
  "Costa Rica": { name: "Costa Rica", code: "CR", code3: "CRI", region: "Americas", subregion: "Central America", passportColor: "blue", flagEmoji: "🇨🇷" },
  "Côte d'Ivoire (Ivory Coast)": { name: "Côte d'Ivoire (Ivory Coast)", code: "CI", code3: "CIV", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇨🇮" },
  "Croatia": { name: "Croatia", code: "HR", code3: "HRV", region: "Europe", subregion: "Southern Europe", passportColor: "red", flagEmoji: "🇭🇷" },
  "Cuba": { name: "Cuba", code: "CU", code3: "CUB", region: "Americas", subregion: "Caribbean", passportColor: "blue", flagEmoji: "🇨🇺" },
  "Cyprus": { name: "Cyprus", code: "CY", code3: "CYP", region: "Europe", subregion: "Southern Europe", passportColor: "red", flagEmoji: "🇨🇾" },
  "Czech Republic": { name: "Czech Republic", code: "CZ", code3: "CZE", region: "Europe", subregion: "Eastern Europe", passportColor: "red", flagEmoji: "🇨🇿" },
  "Denmark": { name: "Denmark", code: "DK", code3: "DNK", region: "Europe", subregion: "Northern Europe", passportColor: "red", flagEmoji: "🇩🇰" },
  "Djibouti": { name: "Djibouti", code: "DJ", code3: "DJI", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇩🇯" },
  "Dominica": { name: "Dominica", code: "DM", code3: "DMA", region: "Americas", subregion: "Caribbean", passportColor: "blue", flagEmoji: "🇩🇲" },
  "Dominican Republic": { name: "Dominican Republic", code: "DO", code3: "DOM", region: "Americas", subregion: "Caribbean", passportColor: "blue", flagEmoji: "🇩🇴" },
  "Ecuador": { name: "Ecuador", code: "EC", code3: "ECU", region: "Americas", subregion: "South America", passportColor: "blue", flagEmoji: "🇪🇨" },
  "Egypt": { name: "Egypt", code: "EG", code3: "EGY", region: "Africa", subregion: "Northern Africa", passportColor: "green", flagEmoji: "🇪🇬" },
  "El Salvador": { name: "El Salvador", code: "SV", code3: "SLV", region: "Americas", subregion: "Central America", passportColor: "blue", flagEmoji: "🇸🇻" },
  "Equatorial Guinea": { name: "Equatorial Guinea", code: "GQ", code3: "GNQ", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇬🇶" },
  "Eritrea": { name: "Eritrea", code: "ER", code3: "ERI", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇪🇷" },
  "Estonia": { name: "Estonia", code: "EE", code3: "EST", region: "Europe", subregion: "Northern Europe", passportColor: "blue", flagEmoji: "🇪🇪" },
  "Eswatini": { name: "Eswatini", code: "SZ", code3: "SWZ", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇸🇿" },
  "Ethiopia": { name: "Ethiopia", code: "ET", code3: "ETH", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇪🇹" },
  "Fiji": { name: "Fiji", code: "FJ", code3: "FJI", region: "Oceania", subregion: "Melanesia", passportColor: "blue", flagEmoji: "🇫🇯" },
  "Finland": { name: "Finland", code: "FI", code3: "FIN", region: "Europe", subregion: "Northern Europe", passportColor: "red", flagEmoji: "🇫🇮" },
  "France": { name: "France", code: "FR", code3: "FRA", region: "Europe", subregion: "Western Europe", passportColor: "red", flagEmoji: "🇫🇷" },
  "Gabon": { name: "Gabon", code: "GA", code3: "GAB", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇬🇦" },
  "Gambia": { name: "Gambia", code: "GM", code3: "GMB", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇬🇲" },
  "Georgia": { name: "Georgia", code: "GE", code3: "GEO", region: "Asia", subregion: "Western Asia", passportColor: "red", flagEmoji: "🇬🇪" },
  "Germany": { name: "Germany", code: "DE", code3: "DEU", region: "Europe", subregion: "Western Europe", passportColor: "red", flagEmoji: "🇩🇪" },
  "Ghana": { name: "Ghana", code: "GH", code3: "GHA", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇬🇭" },
  "Greece": { name: "Greece", code: "GR", code3: "GRC", region: "Europe", subregion: "Southern Europe", passportColor: "red", flagEmoji: "🇬🇷" },
  "Grenada": { name: "Grenada", code: "GD", code3: "GRD", region: "Americas", subregion: "Caribbean", passportColor: "blue", flagEmoji: "🇬🇩" },
  "Guatemala": { name: "Guatemala", code: "GT", code3: "GTM", region: "Americas", subregion: "Central America", passportColor: "blue", flagEmoji: "🇬🇹" },
  "Guinea": { name: "Guinea", code: "GN", code3: "GIN", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇬🇳" },
  "Guinea-Bissau": { name: "Guinea-Bissau", code: "GW", code3: "GNB", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇬🇼" },
  "Guyana": { name: "Guyana", code: "GY", code3: "GUY", region: "Americas", subregion: "South America", passportColor: "blue", flagEmoji: "🇬🇾" },
  "Haiti": { name: "Haiti", code: "HT", code3: "HTI", region: "Americas", subregion: "Caribbean", passportColor: "blue", flagEmoji: "🇭🇹" },
  "Honduras": { name: "Honduras", code: "HN", code3: "HND", region: "Americas", subregion: "Central America", passportColor: "blue", flagEmoji: "🇭🇳" },
  "Hong Kong": { name: "Hong Kong", code: "HK", code3: "HKG", region: "Asia", subregion: "Eastern Asia", passportColor: "blue", flagEmoji: "🇭🇰" },
  "Hungary": { name: "Hungary", code: "HU", code3: "HUN", region: "Europe", subregion: "Eastern Europe", passportColor: "red", flagEmoji: "🇭🇺" },
  "Iceland": { name: "Iceland", code: "IS", code3: "ISL", region: "Europe", subregion: "Northern Europe", passportColor: "blue", flagEmoji: "🇮🇸" },
  "India": { name: "India", code: "IN", code3: "IND", region: "Asia", subregion: "Southern Asia", passportColor: "blue", flagEmoji: "🇮🇳" },
  "Indonesia": { name: "Indonesia", code: "ID", code3: "IDN", region: "Asia", subregion: "South-Eastern Asia", passportColor: "green", flagEmoji: "🇮🇩" },
  "Iran": { name: "Iran", code: "IR", code3: "IRN", region: "Asia", subregion: "Southern Asia", passportColor: "blue", flagEmoji: "🇮🇷" },
  "Iraq": { name: "Iraq", code: "IQ", code3: "IRQ", region: "Asia", subregion: "Western Asia", passportColor: "blue", flagEmoji: "🇮🇶" },
  "Ireland": { name: "Ireland", code: "IE", code3: "IRL", region: "Europe", subregion: "Northern Europe", passportColor: "red", flagEmoji: "🇮🇪" },
  "Israel": { name: "Israel", code: "IL", code3: "ISR", region: "Asia", subregion: "Western Asia", passportColor: "blue", flagEmoji: "🇮🇱" },
  "Italy": { name: "Italy", code: "IT", code3: "ITA", region: "Europe", subregion: "Southern Europe", passportColor: "red", flagEmoji: "🇮🇹" },
  "Jamaica": { name: "Jamaica", code: "JM", code3: "JAM", region: "Americas", subregion: "Caribbean", passportColor: "blue", flagEmoji: "🇯🇲" },
  "Japan": { name: "Japan", code: "JP", code3: "JPN", region: "Asia", subregion: "Eastern Asia", passportColor: "red", flagEmoji: "🇯🇵" },
  "Jordan": { name: "Jordan", code: "JO", code3: "JOR", region: "Asia", subregion: "Western Asia", passportColor: "green", flagEmoji: "🇯🇴" },
  "Kazakhstan": { name: "Kazakhstan", code: "KZ", code3: "KAZ", region: "Asia", subregion: "Central Asia", passportColor: "blue", flagEmoji: "🇰🇿" },
  "Kenya": { name: "Kenya", code: "KE", code3: "KEN", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇰🇪" },
  "Kiribati": { name: "Kiribati", code: "KI", code3: "KIR", region: "Oceania", subregion: "Micronesia", passportColor: "blue", flagEmoji: "🇰🇮" },
  "Kosovo": { name: "Kosovo", code: "XK", code3: "XKX", region: "Europe", subregion: "Southern Europe", passportColor: "blue", flagEmoji: "🇽🇰" },
  "Kuwait": { name: "Kuwait", code: "KW", code3: "KWT", region: "Asia", subregion: "Western Asia", passportColor: "blue", flagEmoji: "🇰🇼" },
  "Kyrgyzstan": { name: "Kyrgyzstan", code: "KG", code3: "KGZ", region: "Asia", subregion: "Central Asia", passportColor: "red", flagEmoji: "🇰🇬" },
  "Laos": { name: "Laos", code: "LA", code3: "LAO", region: "Asia", subregion: "South-Eastern Asia", passportColor: "red", flagEmoji: "🇱🇦" },
  "Latvia": { name: "Latvia", code: "LV", code3: "LVA", region: "Europe", subregion: "Northern Europe", passportColor: "red", flagEmoji: "🇱🇻" },
  "Lebanon": { name: "Lebanon", code: "LB", code3: "LBN", region: "Asia", subregion: "Western Asia", passportColor: "blue", flagEmoji: "🇱🇧" },
  "Lesotho": { name: "Lesotho", code: "LS", code3: "LSO", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇱🇸" },
  "Liberia": { name: "Liberia", code: "LR", code3: "LBR", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇱🇷" },
  "Libya": { name: "Libya", code: "LY", code3: "LBY", region: "Africa", subregion: "Northern Africa", passportColor: "green", flagEmoji: "🇱🇾" },
  "Liechtenstein": { name: "Liechtenstein", code: "LI", code3: "LIE", region: "Europe", subregion: "Western Europe", passportColor: "red", flagEmoji: "🇱🇮" },
  "Lithuania": { name: "Lithuania", code: "LT", code3: "LTU", region: "Europe", subregion: "Northern Europe", passportColor: "red", flagEmoji: "🇱🇹" },
  "Luxembourg": { name: "Luxembourg", code: "LU", code3: "LUX", region: "Europe", subregion: "Western Europe", passportColor: "red", flagEmoji: "🇱🇺" },
  "Macao": { name: "Macao", code: "MO", code3: "MAC", region: "Asia", subregion: "Eastern Asia", passportColor: "green", flagEmoji: "🇲🇴" },
  "Madagascar": { name: "Madagascar", code: "MG", code3: "MDG", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "red", flagEmoji: "🇲🇬" },
  "Malawi": { name: "Malawi", code: "MW", code3: "MWI", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇲🇼" },
  "Malaysia": { name: "Malaysia", code: "MY", code3: "MYS", region: "Asia", subregion: "South-Eastern Asia", passportColor: "blue", flagEmoji: "🇲🇾" },
  "Maldives": { name: "Maldives", code: "MV", code3: "MDV", region: "Asia", subregion: "Southern Asia", passportColor: "green", flagEmoji: "🇲🇻" },
  "Mali": { name: "Mali", code: "ML", code3: "MLI", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇲🇱" },
  "Malta": { name: "Malta", code: "MT", code3: "MLT", region: "Europe", subregion: "Southern Europe", passportColor: "red", flagEmoji: "🇲🇹" },
  "Marshall Islands": { name: "Marshall Islands", code: "MH", code3: "MHL", region: "Oceania", subregion: "Micronesia", passportColor: "blue", flagEmoji: "🇲🇭" },
  "Mauritania": { name: "Mauritania", code: "MR", code3: "MRT", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇲🇷" },
  "Mauritius": { name: "Mauritius", code: "MU", code3: "MUS", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇲🇺" },
  "Mexico": { name: "Mexico", code: "MX", code3: "MEX", region: "Americas", subregion: "Central America", passportColor: "green", flagEmoji: "🇲🇽" },
  "Micronesia": { name: "Micronesia", code: "FM", code3: "FSM", region: "Oceania", subregion: "Micronesia", passportColor: "blue", flagEmoji: "🇫🇲" },
  "Moldova": { name: "Moldova", code: "MD", code3: "MDA", region: "Europe", subregion: "Eastern Europe", passportColor: "blue", flagEmoji: "🇲🇩" },
  "Monaco": { name: "Monaco", code: "MC", code3: "MCO", region: "Europe", subregion: "Western Europe", passportColor: "red", flagEmoji: "🇲🇨" },
  "Mongolia": { name: "Mongolia", code: "MN", code3: "MNG", region: "Asia", subregion: "Eastern Asia", passportColor: "blue", flagEmoji: "🇲🇳" },
  "Montenegro": { name: "Montenegro", code: "ME", code3: "MNE", region: "Europe", subregion: "Southern Europe", passportColor: "blue", flagEmoji: "🇲🇪" },
  "Morocco": { name: "Morocco", code: "MA", code3: "MAR", region: "Africa", subregion: "Northern Africa", passportColor: "green", flagEmoji: "🇲🇦" },
  "Mozambique": { name: "Mozambique", code: "MZ", code3: "MOZ", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇲🇿" },
  "Myanmar": { name: "Myanmar", code: "MM", code3: "MMR", region: "Asia", subregion: "South-Eastern Asia", passportColor: "green", flagEmoji: "🇲🇲" },
  "Namibia": { name: "Namibia", code: "NA", code3: "NAM", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇳🇦" },
  "Nauru": { name: "Nauru", code: "NR", code3: "NRU", region: "Oceania", subregion: "Micronesia", passportColor: "blue", flagEmoji: "🇳🇷" },
  "Nepal": { name: "Nepal", code: "NP", code3: "NPL", region: "Asia", subregion: "Southern Asia", passportColor: "blue", flagEmoji: "🇳🇵" },
  "Netherlands": { name: "Netherlands", code: "NL", code3: "NLD", region: "Europe", subregion: "Western Europe", passportColor: "red", flagEmoji: "🇳🇱" },
  "New Zealand": { name: "New Zealand", code: "NZ", code3: "NZL", region: "Oceania", subregion: "Australia and New Zealand", passportColor: "blue", flagEmoji: "🇳🇿" },
  "Nicaragua": { name: "Nicaragua", code: "NI", code3: "NIC", region: "Americas", subregion: "Central America", passportColor: "blue", flagEmoji: "🇳🇮" },
  "Niger": { name: "Niger", code: "NE", code3: "NER", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇳🇪" },
  "Nigeria": { name: "Nigeria", code: "NG", code3: "NGA", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇳🇬" },
  "North Korea": { name: "North Korea", code: "KP", code3: "PRK", region: "Asia", subregion: "Eastern Asia", passportColor: "blue", flagEmoji: "🇰🇵" },
  "North Macedonia": { name: "North Macedonia", code: "MK", code3: "MKD", region: "Europe", subregion: "Southern Europe", passportColor: "red", flagEmoji: "🇲🇰" },
  "Norway": { name: "Norway", code: "NO", code3: "NOR", region: "Europe", subregion: "Northern Europe", passportColor: "red", flagEmoji: "🇳🇴" },
  "Oman": { name: "Oman", code: "OM", code3: "OMN", region: "Asia", subregion: "Western Asia", passportColor: "blue", flagEmoji: "🇴🇲" },
  "Pakistan": { name: "Pakistan", code: "PK", code3: "PAK", region: "Asia", subregion: "Southern Asia", passportColor: "green", flagEmoji: "🇵🇰" },
  "Palau": { name: "Palau", code: "PW", code3: "PLW", region: "Oceania", subregion: "Micronesia", passportColor: "blue", flagEmoji: "🇵🇼" },
  "Palestine": { name: "Palestine", code: "PS", code3: "PSE", region: "Asia", subregion: "Western Asia", passportColor: "green", flagEmoji: "🇵🇸" },
  "Panama": { name: "Panama", code: "PA", code3: "PAN", region: "Americas", subregion: "Central America", passportColor: "blue", flagEmoji: "🇵🇦" },
  "Papua New Guinea": { name: "Papua New Guinea", code: "PG", code3: "PNG", region: "Oceania", subregion: "Melanesia", passportColor: "blue", flagEmoji: "🇵🇬" },
  "Paraguay": { name: "Paraguay", code: "PY", code3: "PRY", region: "Americas", subregion: "South America", passportColor: "blue", flagEmoji: "🇵🇾" },
  "Peru": { name: "Peru", code: "PE", code3: "PER", region: "Americas", subregion: "South America", passportColor: "red", flagEmoji: "🇵🇪" },
  "Philippines": { name: "Philippines", code: "PH", code3: "PHL", region: "Asia", subregion: "South-Eastern Asia", passportColor: "red", flagEmoji: "🇵🇭" },
  "Poland": { name: "Poland", code: "PL", code3: "POL", region: "Europe", subregion: "Eastern Europe", passportColor: "red", flagEmoji: "🇵🇱" },
  "Portugal": { name: "Portugal", code: "PT", code3: "PRT", region: "Europe", subregion: "Southern Europe", passportColor: "red", flagEmoji: "🇵🇹" },
  "Qatar": { name: "Qatar", code: "QA", code3: "QAT", region: "Asia", subregion: "Western Asia", passportColor: "red", flagEmoji: "🇶🇦" },
  "Romania": { name: "Romania", code: "RO", code3: "ROU", region: "Europe", subregion: "Eastern Europe", passportColor: "red", flagEmoji: "🇷🇴" },
  "Russia": { name: "Russia", code: "RU", code3: "RUS", region: "Europe", subregion: "Eastern Europe", passportColor: "red", flagEmoji: "🇷🇺" },
  "Rwanda": { name: "Rwanda", code: "RW", code3: "RWA", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇷🇼" },
  "Samoa": { name: "Samoa", code: "WS", code3: "WSM", region: "Oceania", subregion: "Polynesia", passportColor: "blue", flagEmoji: "🇼🇸" },
  "San Marino": { name: "San Marino", code: "SM", code3: "SMR", region: "Europe", subregion: "Southern Europe", passportColor: "blue", flagEmoji: "🇸🇲" },
  "São Tomé and Príncipe": { name: "São Tomé and Príncipe", code: "ST", code3: "STP", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇸🇹" },
  "Saudi Arabia": { name: "Saudi Arabia", code: "SA", code3: "SAU", region: "Asia", subregion: "Western Asia", passportColor: "green", flagEmoji: "🇸🇦" },
  "Senegal": { name: "Senegal", code: "SN", code3: "SEN", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇸🇳" },
  "Serbia": { name: "Serbia", code: "RS", code3: "SRB", region: "Europe", subregion: "Southern Europe", passportColor: "red", flagEmoji: "🇷🇸" },
  "Seychelles": { name: "Seychelles", code: "SC", code3: "SYC", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇸🇨" },
  "Sierra Leone": { name: "Sierra Leone", code: "SL", code3: "SLE", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇸🇱" },
  "Singapore": { name: "Singapore", code: "SG", code3: "SGP", region: "Asia", subregion: "South-Eastern Asia", passportColor: "red", flagEmoji: "🇸🇬" },
  "Slovakia": { name: "Slovakia", code: "SK", code3: "SVK", region: "Europe", subregion: "Eastern Europe", passportColor: "red", flagEmoji: "🇸🇰" },
  "Slovenia": { name: "Slovenia", code: "SI", code3: "SVN", region: "Europe", subregion: "Southern Europe", passportColor: "red", flagEmoji: "🇸🇮" },
  "Solomon Islands": { name: "Solomon Islands", code: "SB", code3: "SLB", region: "Oceania", subregion: "Melanesia", passportColor: "blue", flagEmoji: "🇸🇧" },
  "Somalia": { name: "Somalia", code: "SO", code3: "SOM", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇸🇴" },
  "South Africa": { name: "South Africa", code: "ZA", code3: "ZAF", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇿🇦" },
  "South Korea": { name: "South Korea", code: "KR", code3: "KOR", region: "Asia", subregion: "Eastern Asia", passportColor: "green", flagEmoji: "🇰🇷" },
  "South Sudan": { name: "South Sudan", code: "SS", code3: "SSD", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇸🇸" },
  "Spain": { name: "Spain", code: "ES", code3: "ESP", region: "Europe", subregion: "Southern Europe", passportColor: "red", flagEmoji: "🇪🇸" },
  "Sri Lanka": { name: "Sri Lanka", code: "LK", code3: "LKA", region: "Asia", subregion: "Southern Asia", passportColor: "blue", flagEmoji: "🇱🇰" },
  "St. Kitts and Nevis": { name: "St. Kitts and Nevis", code: "KN", code3: "KNA", region: "Americas", subregion: "Caribbean", passportColor: "blue", flagEmoji: "🇰🇳" },
  "St. Lucia": { name: "St. Lucia", code: "LC", code3: "LCA", region: "Americas", subregion: "Caribbean", passportColor: "blue", flagEmoji: "🇱🇨" },
  "St. Vincent and the Grenadines": { name: "St. Vincent and the Grenadines", code: "VC", code3: "VCT", region: "Americas", subregion: "Caribbean", passportColor: "blue", flagEmoji: "🇻🇨" },
  "Sudan": { name: "Sudan", code: "SD", code3: "SDN", region: "Africa", subregion: "Northern Africa", passportColor: "green", flagEmoji: "🇸🇩" },
  "Suriname": { name: "Suriname", code: "SR", code3: "SUR", region: "Americas", subregion: "South America", passportColor: "green", flagEmoji: "🇸🇷" },
  "Sweden": { name: "Sweden", code: "SE", code3: "SWE", region: "Europe", subregion: "Northern Europe", passportColor: "red", flagEmoji: "🇸🇪" },
  "Switzerland": { name: "Switzerland", code: "CH", code3: "CHE", region: "Europe", subregion: "Western Europe", passportColor: "red", flagEmoji: "🇨🇭" },
  "Syria": { name: "Syria", code: "SY", code3: "SYR", region: "Asia", subregion: "Western Asia", passportColor: "green", flagEmoji: "🇸🇾" },
  "Taiwan": { name: "Taiwan", code: "TW", code3: "TWN", region: "Asia", subregion: "Eastern Asia", passportColor: "green", flagEmoji: "🇹🇼" },
  "Tajikistan": { name: "Tajikistan", code: "TJ", code3: "TJK", region: "Asia", subregion: "Central Asia", passportColor: "green", flagEmoji: "🇹🇯" },
  "Tanzania": { name: "Tanzania", code: "TZ", code3: "TZA", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇹🇿" },
  "Thailand": { name: "Thailand", code: "TH", code3: "THA", region: "Asia", subregion: "South-Eastern Asia", passportColor: "red", flagEmoji: "🇹🇭" },
  "Timor-Leste": { name: "Timor-Leste", code: "TL", code3: "TLS", region: "Asia", subregion: "South-Eastern Asia", passportColor: "blue", flagEmoji: "🇹🇱" },
  "Togo": { name: "Togo", code: "TG", code3: "TGO", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "green", flagEmoji: "🇹🇬" },
  "Tonga": { name: "Tonga", code: "TO", code3: "TON", region: "Oceania", subregion: "Polynesia", passportColor: "blue", flagEmoji: "🇹🇴" },
  "Trinidad and Tobago": { name: "Trinidad and Tobago", code: "TT", code3: "TTO", region: "Americas", subregion: "Caribbean", passportColor: "red", flagEmoji: "🇹🇹" },
  "Tunisia": { name: "Tunisia", code: "TN", code3: "TUN", region: "Africa", subregion: "Northern Africa", passportColor: "green", flagEmoji: "🇹🇳" },
  "Turkey": { name: "Turkey", code: "TR", code3: "TUR", region: "Asia", subregion: "Western Asia", passportColor: "red", flagEmoji: "🇹🇷" },
  "Turkmenistan": { name: "Turkmenistan", code: "TM", code3: "TKM", region: "Asia", subregion: "Central Asia", passportColor: "green", flagEmoji: "🇹🇲" },
  "Tuvalu": { name: "Tuvalu", code: "TV", code3: "TUV", region: "Oceania", subregion: "Polynesia", passportColor: "blue", flagEmoji: "🇹🇻" },
  "Uganda": { name: "Uganda", code: "UG", code3: "UGA", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇺🇬" },
  "Ukraine": { name: "Ukraine", code: "UA", code3: "UKR", region: "Europe", subregion: "Eastern Europe", passportColor: "blue", flagEmoji: "🇺🇦" },
  "United Arab Emirates": { name: "United Arab Emirates", code: "AE", code3: "ARE", region: "Asia", subregion: "Western Asia", passportColor: "blue", flagEmoji: "🇦🇪" },
  "United Kingdom": { name: "United Kingdom", code: "GB", code3: "GBR", region: "Europe", subregion: "Northern Europe", passportColor: "red", flagEmoji: "🇬🇧" },
  "United States": { name: "United States", code: "US", code3: "USA", region: "Americas", subregion: "Northern America", passportColor: "blue", flagEmoji: "🇺🇸" },
  "Uruguay": { name: "Uruguay", code: "UY", code3: "URY", region: "Americas", subregion: "South America", passportColor: "blue", flagEmoji: "🇺🇾" },
  "Uzbekistan": { name: "Uzbekistan", code: "UZ", code3: "UZB", region: "Asia", subregion: "Central Asia", passportColor: "green", flagEmoji: "🇺🇿" },
  "Vanuatu": { name: "Vanuatu", code: "VU", code3: "VUT", region: "Oceania", subregion: "Melanesia", passportColor: "blue", flagEmoji: "🇻🇺" },
  "Vatican City": { name: "Vatican City", code: "VA", code3: "VAT", region: "Europe", subregion: "Southern Europe", passportColor: "red", flagEmoji: "🇻🇦" },
  "Venezuela": { name: "Venezuela", code: "VE", code3: "VEN", region: "Americas", subregion: "South America", passportColor: "red", flagEmoji: "🇻🇪" },
  "Vietnam": { name: "Vietnam", code: "VN", code3: "VNM", region: "Asia", subregion: "South-Eastern Asia", passportColor: "green", flagEmoji: "🇻🇳" },
  "Yemen": { name: "Yemen", code: "YE", code3: "YEM", region: "Asia", subregion: "Western Asia", passportColor: "green", flagEmoji: "🇾🇪" },
  "Zambia": { name: "Zambia", code: "ZM", code3: "ZMB", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇿🇲" },
  "Zimbabwe": { name: "Zimbabwe", code: "ZW", code3: "ZWE", region: "Africa", subregion: "Sub-Saharan Africa", passportColor: "blue", flagEmoji: "🇿🇼" },
};

export function getCountryByCode(code: string): CountryMeta | undefined {
  return Object.values(COUNTRIES).find(c => c.code === code.toUpperCase() || c.code3 === code.toUpperCase());
}

export function getCountryByName(name: string): CountryMeta | undefined {
  return COUNTRIES[name];
}

export function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

export function getCountryBySlug(slug: string): CountryMeta | undefined {
  return Object.values(COUNTRIES).find(c => slugify(c.name) === slug);
}

export function getFlagUrl(code: string): string {
  return `https://flagcdn.com/w80/${code.toLowerCase()}.png`;
}

export function getFlagUrlLarge(code: string): string {
  return `https://flagcdn.com/w320/${code.toLowerCase()}.png`;
}

export const REGIONS = [...new Set(Object.values(COUNTRIES).map(c => c.region))].sort();
export const PASSPORT_COLORS = ["red", "blue", "green", "black"] as const;

export const REGION_COLORS: Record<string, string> = {
  "Africa": "#F59E0B",
  "Americas": "#3B82F6",
  "Asia": "#EF4444",
  "Europe": "#8B5CF6",
  "Oceania": "#10B981",
};
